services:
  # Laravel Application
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: survey_app
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/99-custom.ini
    working_dir: /var/www/html
    environment:
      - APP_ENV=local
      - DB_HOST=mysql
      - DB_DATABASE=survey
      - DB_USERNAME=survey
      - DB_PASSWORD=survey
    depends_on:
      - mysql
      - redis
    networks:
      - survey_network

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: survey_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - survey_network

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: survey_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: survey
      MYSQL_USER: survey
      MYSQL_PASSWORD: survey
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - survey_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: survey_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - survey_network

  # Horizon Queue Worker (optional)
  horizon:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: survey_horizon
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: php artisan horizon
    environment:
      - APP_ENV=local
      - DB_HOST=mysql
      - DB_DATABASE=survey
      - DB_USERNAME=survey
      - DB_PASSWORD=survey
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis
      - app
    networks:
      - survey_network

volumes:
  mysql_data:
  redis_data:

networks:
  survey_network:
    driver: bridge
